import type { Airport } from '@/schemas';

import airportsJson from './airports.json';

// Generated by scripts/build-airports.mjs. Every row is checked against AirportSchema in
// src/data/__tests__/airports.test.ts, so the app does not re-parse ~3,000 rows at startup.
export const AIRPORTS: readonly Airport[] = airportsJson;
